# Generated by Django 4.0.4 on 2022-06-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_proveedores_servicios_rename_estudiante_clientes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='nombre',
            new_name='especialidad',
        ),
    ]
